### ISSUE TITLE
Remove global box-sizing reset

### ISSUE THREAD

**Issue by st3phan** [pattern-lab/styleguidekit-assets-default#58]
Could you consider removing the global `box-sizing: border-box` reset declaration?

It sometimes starts messing up layouts because the `styleguide.css` is of course not included in my production project. So where in patternlab the `box-sizing` reset applies to all elements it does not when viewing elements outside of patternlab because there is no global reset in my production CSS. I only set `box-sizing` to `border-box` on elements that need it.

So please consider removing this global box sizing reset:

```css
/*------------------------------------*\
#RESET
\*------------------------------------*/

/**
* Apply border-box to all elements
*
* 1) This is a broadly-applied style that affects every
* element on the screen. This can bleed into user's styles
* but since it's been a best practice for years now we're
* going to default to this.
*/
* {
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}
```

And apply it only to elements that need it:

```css
.sg-input {
    box-sizing: border-box; // apply to element that needs the reset
    margin: -2px 0 0 0;
    padding: 0.1em;
    border: 0;
    border-radius: $sg-border-radius;
    background: $sg-black;
    color: $sg-gray;
    width: 25px;
    text-align: right;
    transition: all $sg-animate-quick ease-out;
    ...
}
