### ISSUE TITLE
Menu triangles do not render correctly on Windows

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/styleguidekit-assets-default#86]
The triangle referenced below do not render correctly on Windows.
Chrome, Firefox, IE11

```css
.pl-c-nav__link--dropdown {

    /**
    * Dropdown caret after accordion handle
    */
    &:after {
        content: '▼';
        color: $pl-color-trans-white-25;
        display: inline-block;
        font-size: 7px;
        position: relative;
        top: 1px;
        right: -2px;
        transition: all $pl-animate-quick ease-out;
    }
```

![image](https://user-images.githubusercontent.com/298435/31370029-1764c692-ad4e-11e7-82b8-0667a0bff8ea.png)
